# Generated by Django 2.1.3 on 2019-12-19 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prova', models.TextField(choices=[('LC', 'Linguagens e códigos'), ('MT', 'Matématica e suas Tecnologias'), ('CH', 'Ciências Humanas'), ('CN', 'Ciências da Natureza'), ('REDACAO', 'Redação')], max_length=255)),
                ('frequencia', models.IntegerField()),
                ('media', models.FloatField(default=0.0)),
                ('variancia', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Percentil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('frequencia', models.IntegerField()),
                ('media', models.FloatField(default=0.0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percentis', to='enem.Area')),
            ],
            options={
                'verbose_name_plural': 'Percentis',
            },
        ),
        migrations.CreateModel(
            name='TipoPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_raca', models.CharField(choices=[('0', 'Não declarado'), ('1', 'Branca'), ('2', 'Preta'), ('3', 'Parda'), ('4', 'Amarela'), ('5', 'Indígena')], max_length=20)),
                ('tipo_escola', models.CharField(choices=[('1', 'Não informada'), ('2', 'Pública'), ('3', 'Privada'), ('4', 'Exterior')], max_length=50)),
                ('renda_familiar', models.CharField(choices=[('A', 'Nenhuma'), ('B', 'Até R$937,00'), ('C', 'de R$937,01 até R$1.405,50'), ('D', 'de R$1.405,51 até R$1.874,00'), ('E', 'de R$1.874,01 até R$2.342,50'), ('F', 'de R$2.342,51 até R$2.811,00'), ('G', 'de R$2.811,01 até R$3.748,00'), ('H', 'de R$3.748,01 até R$4.685,00'), ('I', 'de R$4.685,01 até R$5.622,00'), ('J', 'de R$5.622,01 até R$6.559,00'), ('K', 'de R$6.559,01 até R$7.496,00'), ('L', 'de R$7.496,01 até R$8.433,00'), ('M', 'de R$8.433,01 até R$9.370,00'), ('N', 'de R$9.370,01 até R$11.244,00'), ('O', 'de R$11.244,01 até R$14.055,00'), ('P', 'de R$14.055,01 até R$18.740,00'), ('Q', 'Acima de R$18.740,01')], max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Perfil',
                'verbose_name_plural': 'Tipos de Perfis',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='enem.TipoPerfil'),
        ),
    ]
