# Generated by Django 2.1.3 on 2019-12-19 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_natureza', models.FloatField(default=0.0)),
                ('nota_humanas', models.FloatField(default=0.0)),
                ('nota_matematica', models.FloatField(default=0.0)),
                ('nota_linguagens', models.FloatField(default=0.0)),
                ('nota_redacao', models.FloatField(default=0.0)),
                ('tipo_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='enem.TipoPerfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
