# Generated by Django 2.1.3 on 2020-01-02 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200101_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='provas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provas', to='core.Prova'),
        ),
    ]
