# Generated by Django 2.1.3 on 2020-01-02 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200101_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='provas',
        ),
        migrations.AddField(
            model_name='prova',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provas', to='core.Perfil'),
            preserve_default=False,
        ),
    ]
