# Generated by Django 2.1.3 on 2020-01-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200101_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='prova',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas', to='core.Perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='core.Escola'),
        ),
    ]
