# Generated by Django 2.1.3 on 2020-01-04 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20200102_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escola', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
