# Generated by Django 2.1.3 on 2019-12-19 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.TextField(max_length=255)),
                ('turno', models.TextField(max_length=255)),
                ('grau', models.TextField(max_length=255)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='sisu.Campus')),
            ],
            options={
                'ordering': ('nome', '-campus__ies__nome'),
            },
        ),
        migrations.CreateModel(
            name='Ies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ies',
                'verbose_name_plural': 'Ies',
                'ordering': ('sigla',),
            },
        ),
        migrations.CreateModel(
            name='ModalidadeCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(max_length=100)),
                ('nota_corte', models.FloatField()),
                ('descricao', models.TextField(blank=True, max_length=255)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='sisu.Curso')),
            ],
            options={
                'verbose_name': 'Modalidade Curso',
                'verbose_name_plural': 'Modalidades Curso',
            },
        ),
        migrations.CreateModel(
            name='PesoCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.TextField(choices=[('Ciências da Natureza e suas Tecnologias', 'Ciências da Natureza e suas Tecnologias'), ('Ciências Humanas e suas Tecnologias', 'Ciências Humanas e suas Tecnologias'), ('Linguagens, Códigos e suas Tecnologias', 'Linguagens, Códigos e suas Tecnologias'), ('Matemática e suas Tecnologias', 'Matemática e suas Tecnologias'), ('Redação', 'Redação')], max_length=100)),
                ('peso', models.FloatField(default=0.0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos', to='sisu.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='campus',
            name='ies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campi', to='sisu.Ies'),
        ),
    ]
